### ISSUE TITLE
GtR server update has broken all functionality

### ISSUE THREAD

**Issue by MOLAMixedReality** [MatthewSmith430/GtR#2]
Edits to the GtR API following the server update from May 2024 has broken all functionality within this package. 

1) the API end point of GTR has changed default data type returned to XML, header flags need to be added to GET requests for all functions to specifically return JSON data. 

e.g. GtR_project_extract_function.R line 9: 
firmTEST<-httr::GET(url, add_headers("Accept: application/vnd.rcuk.gtr.json-v7"))

2) The schema for their fieldnames has also changed breaking 'if' loops e.g. Project Extract function and Further Funding function (I have only tested these there could be more) - specifically for those 2 functions the suffix 'Output' on fieldnames is now 'Outputs'. Example screenshots attached.

![image](https://github.com/user-attachments/assets/d7b3350e-e009-4e57-a20b-323db4229b40)
![image](https://github.com/user-attachments/assets/242f76d2-23b5-4719-bd53-9bf64b435cd3)
![image](https://github.com/user-attachments/assets/073b3802-fd5a-4344-a0e6-97148f90886e)

**Comment by MatthewSmith430** [comment]
Thank you for highlighting this and providing the suggested solution - it is greatly appreciated. The functions have been revised, incorporating this and the new api requirements.
